#!/usr/bin/env python3
"""Build the Fastly API tube-style map.

Generated by batch generator. 
"""

import sys
from pathlib import Path

sys.path.insert(0, "/Users/kinlane/GitHub/all/.claude/skills")
from _subway_engine import build_subway  # noqa: E402

ABBREV = {
    'Metrics & Stats': 'Metrics',
    'Auth Tokens': 'Auth Tokens',
}

LINES = [
    {
        "name": 'Edge Delivery',
        "color": '#FF282D',
        "stations": [
        ('Services', (270, 200)),
        ('Compute', (430, 175)),
        ('Domains', (590, 165)),
        ('VCL Services', (760, 175)),
        ('Products', (940, 200)),
        ],
    },
    {
        "name": 'Operations & Logging',
        "color": '#1E5BD0',
        "stations": [
        ('Purging', (270, 320)),
        ('Logging', (430, 295)),
        ('Metrics & Stats', (610, 295)),
        ('Dictionaries', (790, 295)),
        ('ACLs', (960, 320)),
        ],
    },
    {
        "name": 'Security & Identity',
        "color": '#5A6275',
        "closed": True,
        "stations": [
        ('TLS', (820, 480)),
        ('WAF', (910, 555)),
        ('Auth Tokens', (730, 555)),
        ('Account', (820, 630)),
        ],
    },
]

URL_OVERRIDES = {
    'Services': 'https://apis.apis.io/apis/fastly/services-api/',
    'Purging': 'https://apis.apis.io/apis/fastly/purging-api/',
    'Logging': 'https://apis.apis.io/apis/fastly/logging-api/',
    'Metrics & Stats': 'https://apis.apis.io/apis/fastly/metrics-and-stats-api/',
    'TLS': 'https://apis.apis.io/apis/fastly/tls-api/',
    'VCL Services': 'https://apis.apis.io/apis/fastly/vcl-services-api/',
    'Account': 'https://apis.apis.io/apis/fastly/account-api/',
    'Auth Tokens': 'https://apis.apis.io/apis/fastly/authentication-tokens-api/',
    'ACLs': 'https://apis.apis.io/apis/fastly/acls-api/',
    'Dictionaries': 'https://apis.apis.io/apis/fastly/dictionaries-api/',
    'Compute': 'https://apis.apis.io/apis/fastly/compute-api/',
    'WAF': 'https://apis.apis.io/apis/fastly/waf-api/',
    'Domains': 'https://apis.apis.io/apis/fastly/domain-management-api/',
    'Products': 'https://apis.apis.io/apis/fastly/products-api/',
}


def main():
    seen = set()
    n_unique = 0
    for ln in LINES:
        for (st, _) in ln["stations"]:
            if st not in seen:
                n_unique += 1
                seen.add(st)
    build_subway(
        title='The Fastly API · Underground Map',
        subtitle=f"{n_unique} APIs · {len(LINES)} functional lines · click any station for the apis.io page",
        lines=LINES,
        abbrev=ABBREV,
        source_label='Source: fastly/openapi · github.com/api-evangelist/fastly',
        out_dir=Path(__file__).resolve().parent,
        out_basename='fastly-subway-map',
        provider_id='fastly',
        station_url_overrides=URL_OVERRIDES,
    )


if __name__ == "__main__":
    main()
