openapi: 3.2.0
info:
  title: Fastly Utilities Diff API
  description: 'The Fastly Utilities API covers various utilities and extra functionality

    provided in addition to the configuration services. Endpoints include

    Content Status, Diff, Docs, POPs, Public IP List, and Sudo Mode.'
  version: 1.0.0
servers:
- url: https://api.fastly.com
security:
- FastlyKey: []
tags:
- name: Diff
paths:
  /service/{service_id}/diff/from/{from_version}/to/{to_version}:
    parameters:
    - in: path
      name: service_id
      required: true
      schema:
        type: string
    - in: path
      name: from_version
      required: true
      schema:
        type: integer
    - in: path
      name: to_version
      required: true
      schema:
        type: integer
    get:
      tags:
      - Diff
      summary: Diff Service Versions
      operationId: diffServiceVersions
      responses:
        '200':
          description: Line-by-line configuration differences
components:
  securitySchemes:
    FastlyKey:
      type: apiKey
      in: header
      name: Fastly-Key
