openapi: 3.2.0
info:
  title: Fastly Utilities Public IP List API
  description: 'The Fastly Utilities API covers various utilities and extra functionality

    provided in addition to the configuration services. Endpoints include

    Content Status, Diff, Docs, POPs, Public IP List, and Sudo Mode.'
  version: 1.0.0
servers:
- url: https://api.fastly.com
security:
- FastlyKey: []
tags:
- name: Public IP List
paths:
  /public-ip-list:
    get:
      tags:
      - Public IP List
      summary: Get Fastly Public IP Ranges
      operationId: getPublicIpList
      responses:
        '200':
          description: Fastly's assigned IP ranges for firewall rules
          content:
            application/json:
              schema:
                type: object
                properties:
                  addresses:
                    type: array
                    items:
                      type: string
                      example: 23.235.32.0/20
                  ipv6_addresses:
                    type: array
                    items:
                      type: string
components:
  securitySchemes:
    FastlyKey:
      type: apiKey
      in: header
      name: Fastly-Key
