openapi: 3.2.0
info:
  title: Fastly Utilities Docs API
  description: 'The Fastly Utilities API covers various utilities and extra functionality

    provided in addition to the configuration services. Endpoints include

    Content Status, Diff, Docs, POPs, Public IP List, and Sudo Mode.

    '
  version: 1.0.0
servers:
- url: https://api.fastly.com
security:
- FastlyKey: []
tags:
- name: Docs
paths:
  /docs:
    get:
      tags:
      - Docs
      summary: Get API Documentation
      operationId: getApiDocs
      responses:
        '200':
          description: Fastly API documentation
components:
  securitySchemes:
    FastlyKey:
      type: apiKey
      in: header
      name: Fastly-Key
