openapi: 3.2.0
info:
  title: Fastly Observability Log Explorer API
  description: 'The Fastly Observability APIs enable you to setup and manage Fastly''s

    Observability features on your site, product or service across all Network

    Services, Compute and Security product lines. Sub-resources include Alerts,

    Custom Dashboards, Insights, Log Aggregations, Log Explorer, Notification

    Service, and Timeseries.'
  version: 1.0.0
  contact:
    name: Fastly Support
    url: https://support.fastly.com
servers:
- url: https://api.fastly.com
  description: Fastly Production API
security:
- FastlyKey: []
tags:
- name: Log Explorer
paths:
  /observability/logs:
    post:
      tags:
      - Log Explorer
      summary: Search Logs
      operationId: searchLogs
      responses:
        '200':
          description: Log search results
components:
  securitySchemes:
    FastlyKey:
      type: apiKey
      in: header
      name: Fastly-Key
