openapi: 3.2.0
info:
  title: Fastly DDoS Protection Events Traffic Stats API
  description: 'The Fastly DDoS Protection Events API allows you to configure Fastly DDoS

    Protection and view attack insights including events, rules, and traffic

    statistics. Endpoints are exposed under /ddos-protection/v1/.

    '
  version: 1.0.0
servers:
- url: https://api.fastly.com
security:
- FastlyKey: []
tags:
- name: Traffic Stats
paths:
  /ddos-protection/v1/events/{event_id}/rules/{rule_id}/traffic-stats:
    parameters:
    - in: path
      name: event_id
      required: true
      schema:
        type: string
    - in: path
      name: rule_id
      required: true
      schema:
        type: string
    get:
      tags:
      - Traffic Stats
      summary: Get Traffic Stats For A Rule
      operationId: getTrafficStatsForRule
      responses:
        '200':
          description: Traffic statistics
components:
  securitySchemes:
    FastlyKey:
      type: apiKey
      in: header
      name: Fastly-Key
