openapi: 3.2.0
info:
  title: Fastly Observability Insights API
  description: 'The Fastly Observability APIs enable you to setup and manage Fastly''s

    Observability features on your site, product or service across all Network

    Services, Compute and Security product lines. Sub-resources include Alerts,

    Custom Dashboards, Insights, Log Aggregations, Log Explorer, Notification

    Service, and Timeseries.'
  version: 1.0.0
  contact:
    name: Fastly Support
    url: https://support.fastly.com
servers:
- url: https://api.fastly.com
  description: Fastly Production API
security:
- FastlyKey: []
tags:
- name: Insights
paths:
  /observability/insights:
    get:
      tags:
      - Insights
      summary: List Insights
      operationId: listInsights
      responses:
        '200':
          description: Insight summaries
components:
  securitySchemes:
    FastlyKey:
      type: apiKey
      in: header
      name: Fastly-Key
